/* SELECT * FROM Q_REPLY; */

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE Q_REPLY;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Q_REPLY(
	R_NO DOUBLE AUTO_INCREMENT PRIMARY KEY,
	R_WRITER VARCHAR(100) NOT NULL,
	R_REWRITER VARCHAR(100),
	R_CONTENT VARCHAR(4000),
	R_DATE TIMESTAMP,
	R_EDITDATE TIMESTAMP,
	R_DELETE DOUBLE,						
	R_GROUP DOUBLE,						
	R_GROUPORD DOUBLE,					
	R_DEPTH DOUBLE,					
	R_Q_NO DOUBLE REFERENCES QNA (Q_NO) ON DELETE CASCADE,
	R_M_NO DOUBLE REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);

/* INSERT */
INSERT INTO Q_REPLY(R_WRITER, R_REWRITER, R_CONTENT, R_DATE, R_EDITDATE, R_DELETE, R_GROUP, R_GROUPORD, R_DEPTH, R_Q_NO, R_M_NO) VALUES('관리자1',NULL,'원래 재질이 그렇습니다^^',NOW(),NOW(),0,1,0,0,1,1);
INSERT INTO Q_REPLY(R_WRITER, R_REWRITER, R_CONTENT, R_DATE, R_EDITDATE, R_DELETE, R_GROUP, R_GROUPORD, R_DEPTH, R_Q_NO, R_M_NO) VALUES('홍길동',NULL,'환불해주세요',NOW(),NOW(),0,1,1,1,1,4);
INSERT INTO Q_REPLY(R_WRITER, R_REWRITER, R_CONTENT, R_DATE, R_EDITDATE, R_DELETE, R_GROUP, R_GROUPORD, R_DEPTH, R_Q_NO, R_M_NO) VALUES('관리자2',NULL,'손상된 제품 환불이 어렵습니다~',NOW(),NOW(),0,1,2,2,1,2);
