/* SELECT * FROM REVIEWS; */

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE REVIEWS;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE REVIEWS(
	RV_NO DOUBLE AUTO_INCREMENT PRIMARY KEY,				
	RV_TITLE VARCHAR(100) NOT NULL,				
	RV_CONTENT VARCHAR(500) NOT NULL,		
	RV_REGDATE TIMESTAMP NOT NULL,					
	RV_HIT DOUBLE NOT NULL,					
	RV_FILENAME VARCHAR(300),					
	RV_M_NO DOUBLE NOT NULL,			
	RV_P_NO DOUBLE NOT NULL,				
	FOREIGN KEY (RV_M_NO) REFERENCES MEMBERS (M_NO),
	FOREIGN KEY (RV_P_NO) REFERENCES PRODUCT (P_NO)	
);

/* INSERT */
INSERT INTO REVIEWS(RV_TITLE, RV_CONTENT, RV_REGDATE, RV_HIT, RV_FILENAME, RV_M_NO, RV_P_NO) VALUES('정말좋네요','옷입어봤는데너무좋아요',NOW(),0,'review1.jpg',4,20);
INSERT INTO REVIEWS(RV_TITLE, RV_CONTENT, RV_REGDATE, RV_HIT, RV_FILENAME, RV_M_NO, RV_P_NO) VALUES('이뻐요요','잘입고있어요',NOW(),0,'review2.jpg',4,13);

INSERT INTO REVIEWS(RV_TITLE, RV_CONTENT, RV_REGDATE, RV_HIT, RV_FILENAME, RV_M_NO, RV_P_NO) VALUES('생각보다별로에요','후회합니다',NOW(),0,'review2.jpg',5,12);
INSERT INTO REVIEWS(RV_TITLE, RV_CONTENT, RV_REGDATE, RV_HIT, RV_FILENAME, RV_M_NO, RV_P_NO) VALUES('정말좋네요','옷입어봤는데너무좋아요',NOW(),0,'review3.jpg',5,23);
INSERT INTO REVIEWS(RV_TITLE, RV_CONTENT, RV_REGDATE, RV_HIT, RV_FILENAME, RV_M_NO, RV_P_NO) VALUES('괜찮아요','매우괜찮아요',NOW(),0,'review4.jpg',5,17);
INSERT INTO REVIEWS(RV_TITLE, RV_CONTENT, RV_REGDATE, RV_HIT, RV_FILENAME, RV_M_NO, RV_P_NO) VALUES('상당합니다','상당히 좋아요우',NOW(),0,'review2.jpg',5,14);
INSERT INTO REVIEWS(RV_TITLE, RV_CONTENT, RV_REGDATE, RV_HIT, RV_FILENAME, RV_M_NO, RV_P_NO) VALUES('정말좋아요','네 정말입니다',NOW(),0,'review5.jpg',5,30);

INSERT INTO REVIEWS(RV_TITLE, RV_CONTENT, RV_REGDATE, RV_HIT, RV_FILENAME, RV_M_NO, RV_P_NO) VALUES('매우좋아요','매우입니다',NOW(),0,'review5.jpg',6,31);
INSERT INTO REVIEWS(RV_TITLE, RV_CONTENT, RV_REGDATE, RV_HIT, RV_FILENAME, RV_M_NO, RV_P_NO) VALUES('입어보니알겠어요','입어보세요',NOW(),0,'review6.jpg',6,9);